In [1]:
import pandas as pd

# 1. Memuat Dataset
df = pd.read_csv('SampleSuperstore.csv')

# Menampilkan informasi dasar (tipe data dan missing values)
print("--- Info Dataset ---")
df.info()

# 2. Analisis Statistik Dasar (Numerik)
print("\n--- Ringkasan Statistik Dasar ---")
# Fungsi describe() otomatis menghitung Mean, Min, Max, Standar Deviasi, dan Kuartil (25%, 50%/Median, 75%)
display(df.describe())

# 3. Menghitung Modus
print("\n--- Modus Variabel Numerik ---")
display(df[['Sales', 'Quantity', 'Discount', 'Profit']].mode())

# 4. Praktik Exploratory Data Analysis (Kategorikal)
# Menggunakan value_counts() untuk melihat proporsi
print("\n--- Transaksi per Kategori (value_counts) ---")
display(df['Category'].value_counts())

# Menggunakan unique() untuk melihat nilai unik dalam bentuk array
print("\n--- Daftar Kategori Unik (unique) ---")
display(df['Category'].unique())

# Menggunakan nunique() untuk menghitung total nilai unik
print("\n--- Jumlah Sub-Kategori Unik (nunique) ---")
print(f"Total Sub-Kategori: {df['Sub-Category'].nunique()}")

--- Info Dataset ---
<class 'pandas.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Ship Mode     9994 non-null   str
 1   Segment       9994 non-null   str
 2   Country       9994 non-null   str
 3   City          9994 non-null   str
 4   State         9994 non-null   str
 5   Postal Code   9994 non-null   int64
 6   Region        9994 non-null   str
 7   Category      9994 non-null   str
 8   Sub-Category  9994 non-null   str
 9   Sales         9994 non-null   float64
 10  Quantity      9994 non-null   int64
 11  Discount      9994 non-null   float64
 12  Profit        9994 non-null   float64
dtypes: float64(3), int64(2), str(8)
memory usage: 1.7 MB

--- Ringkasan Statistik Dasar ---

        Postal Code         Sales     Quantity     Discount       Profit
count   9994.000000   9994.000000  9994.000000  9994.000000  9994.000000
mean   55190.379428    229.858001     3.789574     0.156203    28.656896
std    32063.693350    623.245101     2.225110     0.206452   234.260108
min     1040.000000      0.444000     1.000000     0.000000 -6599.978000
25%    23223.000000     17.280000     2.000000     0.000000     1.728750
50%    56430.500000     54.490000     3.000000     0.200000     8.666500
75%    90008.000000    209.940000     5.000000     0.200000    29.364000
max    99301.000000  22638.480000    14.000000     0.800000  8399.976000

--- Modus Variabel Numerik ---

   Sales  Quantity  Discount  Profit
0  12.96         3       0.0     0.0

--- Transaksi per Kategori (value_counts) ---

Category
Office Supplies    6026
Furniture          2121
Technology         1847
Name: count, dtype: int64

--- Daftar Kategori Unik (unique) ---

<ArrowStringArray>
['Furniture', 'Office Supplies', 'Technology']
Length: 3, dtype: str

--- Jumlah Sub-Kategori Unik (nunique) ---
Total Sub-Kategori: 17